### ISSUE TITLE
Old port map Overrides external port

### ISSUE THREAD

**Issue by nakaji-s** [cloudfoundry-incubator/tcp-emitter#1]
I have tried the following commands.

```
$ sudo ltc create testUbuntu rastasheep/ubuntu-sshd --tcp-routes 9098:22 -r
$ ltc update --tcp-routes 9099:22 testUbuntu
$ sudo ltc create lattice-app cloudfoundry/lattice-app --tcp-routes 9098:8080
$ ltc scale testUbuntu 2
$ curl 192.168.80.100.xip.io:9098
```

I was intended to get response from lattice-app, but testUbuntu returned.
I think UnsetRoutes() is needed in handleDesiredUpdate().
https://github.com/cloudfoundry-incubator/tcp-emitter/blob/c2553d30b1cff5152bbf7a66bca8f6658ba1ebae/routing_table/routing_table_handler.go#L209

**Comment by shalako** [comment]
Hello @nakaji-s, this is a known issue. We initially added support for creation of TCP routes in Lattice but not deletion of TCP routes. Deletion was recently been completed in [cf-routing-release](https://github.com/cloudfoundry-incubator/cf-routing-release/), and will be pulled into Lattice soon.

**Comment by Nino-K** [comment]
Closing this since [lattice](http://lattice.cf/) is no longer actively maintained and is now deprecated.

Thanks,
@flawedmatrix & Nino
